# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f63f43306cf8d1258e4d8049a3b2407be150c1bdfe407dbdcafdac68148fa96032a15cf0c13c972bbb99ae92d986c4949b32da84b5ccc0a053367ee5ffbcc98

test:
  secret_key_base: 06e1c3a1350315f62dd69f423629c66507cf55f732e9e900190137bdcfdba1eae8b6c02dd02c236944d0f92301be81c6d12c79f4e72a829b5dbb75f69df7c610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
